name: Matheus Massa
description: "Antes de começarmos, um café por favor"
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: 
domain_name: "http://matheusmassa.in"
google_analytics: 
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Matheus Massa"

# Disqus config
disqus-shortname: ""
